GET http://localhost:3000/user/users

###


GET http://localhost:3000/user/user/asdfaousdfg


###

POST http://localhost:3000/user/user
Content-Type: application/json

{
    "name": "인코딩플러스",
    "gender": "남",
    "photo": "https://typeorm.io/"
}

### 

GET http://localhost:3000/user/user/3bead6f7-abcd-4c51-8676-996f030fa357

###

POST http://localhost:3000/post/post/
Content-Type: application/json

{
    "url": "http://post"
}


###
GET http://localhost:3000/oauth/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbmdodW5qaW4xOTE2QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BSXRidm1rLXcza3JoY0tSMWFuRk1hVVhsck1lU09UclpyT0c5VXM5ampScD1zOTYtYyIsIm5hbWUiOiJTQU5HSE9PTiBDSElOIiwiaWF0IjoxNjYxMTcwMDE0LCJleHAiOjE2NjM3NjIwMTR9.27w45pDZ_hzlEiTSX_SLFuhEe2bSlkg3BxcivKWI8cs